### local ###
spring:
  profiles:
    active: "local"
  datasource:
    url: jdbc:mysql://localhost:3306?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password:
    dbcp2:
      driver-class-name: com.mysql.cj.jdbc.Driver